# Generated by Django 5.2.4 on 2025-08-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_alter_tweet_title_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
