# Generated by Django 5.2.4 on 2025-08-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
