# Generated by Django 5.2.4 on 2025-08-07 08:51

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_alter_tweet_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='gener',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('anime', 'Anime'), ('study', 'Study'), ('science', 'Science'), ('technology', 'Technology')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
