# Generated by Django 5.2.4 on 2025-08-07 09:22

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gener',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('anime', 'Anime'), ('study', 'Study'), ('science', 'Science'), ('technology', 'Technology'), ('nature', 'Nature')], max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='gener',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('anime', 'Anime'), ('study', 'Study'), ('science', 'Science'), ('technology', 'Technology'), ('nature', 'Nature')], max_length=37, null=True),
        ),
    ]
