# Generated by Django 5.2.4 on 2025-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_alter_profile_gener_alter_tweet_gener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.FileField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
